### ISSUE TITLE
Need some other keys. Possible?

### ISSUE THREAD

**Issue by LirenGao** [Jl4cTuk/MINI-KeyBoard-V02.1.1#1]
key code KC_YEN, KC_RO are not available.
can they be added?

**Comment by Jl4cTuk** [comment]
![image](https://github.com/user-attachments/assets/3399cf65-0778-4a7c-b3a3-b7f2bdcf97c8)

**Comment by Jl4cTuk** [comment]
This isn’t my software. I ordered a macro keyboard but didn’t know how to use it. When I tried to return it, the seller provided the software for configuration. To keep it, I’m sharing it here since it’s not available for download anywhere else.
