### ISSUE TITLE
False Positive Detection: Binariess contain MaxSecure Trojan.Malware.300983.susgen, Panda PUP/Hacktool

### ISSUE THREAD

**Issue by TechHoruser** [Jl4cTuk/MINI-KeyBoard-V02.1.1#2]
It has come to my attention that the binaries in this repository are being flagged by antivirus software as containing the following threats:

MaxSecure Trojan.Malware.300983.susgen
Panda PUP/Hacktool
These detections are causing security concerns and false positives when scanning the repository. Please review the binaries and verify if any issues exist.

Here is the link to the detailed report for reference: [VirusTotal link](https://www.virustotal.com/gui/file/4ae53d3a40921e4f57444c489fa1b38fe91a2e907feda17630450fc97a7cd7b1).

It would be helpful to investigate if these are indeed false positives or if further action is required.

Thank you for your attention to this matter!

**Comment by Jl4cTuk** [comment]
I ordered a macro keyboard on AliExpress. Who knows what the Chinese developers might have added to the configuration app for the keyboard. It's possible that the developers forgot to remove built-in tools and various debugging elements. I can’t find the seller anymore to ask about it.
